# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 17:05
from __future__ import unicode_literals

import SharingWeb.fields
from django.conf import settings
import django.contrib.auth.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=300)),
                ('attr_format', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=300)),
                ('condition', SharingWeb.fields.IntegerRangeField()),
                ('price', models.IntegerField()),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharingWeb.Category')),
            ],
            options={
                'ordering': ('category', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ItemComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('body', models.CharField(max_length=300)),
                ('stars', SharingWeb.fields.IntegerRangeField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharingWeb.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(upload_to='')),
            ],
            options={
                'ordering': ('id',),
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=300)),
                ('UserRecipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='SharingWeb.ItemUser')),
                ('UserWriter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='SharingWeb.ItemUser')),
            ],
            options={
                'ordering': ('UserRecipient',),
            },
        ),
        migrations.AddField(
            model_name='itemcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharingWeb.ItemUser'),
        ),
        migrations.AddField(
            model_name='itemcomment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharingWeb.Item'),
        ),
    ]
